import torch
import numpy as np
import json
import os
import sys

# Constants matching utils1.py
STEPS_PER_SECOND = 100
NUM_VELOCITY_BINS = 64
MIN_PITCH = 21
MAX_PITCH = 108

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CHECKPOINT_PATH = os.path.join(BASE_DIR, 'params', 'MusicVAE_50.pt')
CONFIG_PATH = os.path.join(BASE_DIR, 'MusicVAE.json')
# Latent generated by Text2Music
LATENT_PATH = "D:/Projects/URIS/URIS/WEMOM_V1/Data/All_Data/test_single_music.npy"
OUTPUT_MIDI_PATH = "D:/Projects/URIS/URIS/WEMOM_V1/generated_midis/music_reconstructed.mid"

# Ensure imports work
sys.path.append(BASE_DIR)

from WEMOM_V1.EmoMusic.MusicVAE import MusicAttrRegGMVAE
from MidiPerformanceEncoder import MidiPerformanceEncoder

def reconstruct():
    # 1. Config
    if not os.path.exists(CONFIG_PATH):
        print(f"Config not found: {CONFIG_PATH}")
        return
    
    with open(CONFIG_PATH) as f:
        args = json.load(f)
        
    print(f"Loading Config: {args}")

    # ============================================================
    # CONFIGURATION
    # ============================================================
    # 长度控制: 100 steps = 1 second. 
    STEPS = 1600 
    
    # [HCI INTERACTIVE SIMULATION]
    # Set these values to simulate User Input via Sliders
    USER_VALENCE = 0.8  # Range [-1.0, 1.0]. Positive = Happy/Major, Negative = Sad/Minor
    USER_AROUSAL = 0.6  # Range [-1.0, 1.0]. High = Fast/Loud, Low = Slow/Soft
    
    # 采样控制:
    # 纯 ArgMax (False) 导致模型陷入 TimeShift 循环（全静音）。
    # 必须开启 Sampling (True)，但使用 Temperature 降低混乱度。
    USE_SAMPLING = True
    TEMPERATURE = 0.7 # Lowering to 0.7 (was 0.85) to reduce "randomness/mashing"
    
    # 后处理过滤:
    # 使用 MusicTheoryFilter 进行节奏量化和调性修正 (Key Snapping)
    USE_FILTER = True
    # ============================================================

    # 2. Dimensions
    # Note: These must match what was used during training/encoding
    # EVENT_DIMS calculation:
    # 2 (reserved) + (108-21+1) NoteOn + (108-21+1) NoteOff + 100 TimeShift + 64 Velocity
    # 2 + 88 + 88 + 100 + 64 = 342
    EVENT_DIMS = 342
    
    RHYTHM_DIMS = 3
    NOTE_DIMS = 16
    CHROMA_DIMS = 24
    DYNAMIC_DIMS = 5
    CHORD_DIMS = 24
    
    # 3. Initialize Model
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")
    
    model = MusicAttrRegGMVAE(
        roll_dims=EVENT_DIMS,
        rhythm_dims=RHYTHM_DIMS,
        note_dims=NOTE_DIMS,
        chroma_dims=CHROMA_DIMS,
        dynamic_dims=DYNAMIC_DIMS,
        chord_dims=CHORD_DIMS,
        hidden_dims=args['hidden_dim'],
        z_dims=args['z_dim'],
        n_step=args['time_step'],
        n_component=args['num_clusters']
    ).to(device)
    
    # Initialize MPE early
    mpe = MidiPerformanceEncoder(
        steps_per_second=STEPS_PER_SECOND,
        num_velocity_bins=NUM_VELOCITY_BINS,
        min_pitch=MIN_PITCH,
        max_pitch=MAX_PITCH,
        add_eos=True
    )
    
    # 4. Load Checkpoint
    if not os.path.exists(CHECKPOINT_PATH):
        print(f"Checkpoint not found: {CHECKPOINT_PATH}")
        return
        
    print(f"Loading Checkpoint: {CHECKPOINT_PATH}")
    checkpoint = torch.load(CHECKPOINT_PATH, map_location=device)
    if 'model_state_dict' in checkpoint:
        model.load_state_dict(checkpoint['model_state_dict'])
    else:
        model.load_state_dict(checkpoint)
        
    model.eval()
    
    # 5. Load Generated Latent
    if not os.path.exists(LATENT_PATH):
        print(f"Latent file not found: {LATENT_PATH}")
        return
        
    print(f"Loading latent: {LATENT_PATH}")
    z = np.load(LATENT_PATH)
    
    # Check shape
    if z.ndim == 1:
        z = z.reshape(1, -1)
    
    # Print Stats
    print(f"Latent Stats - Shape: {z.shape}")
    print(f"Mean: {z.mean():.4f}, Std: {z.std():.4f}")
    
    # --- DEBUG: Load Ground Truth (GT) and try to reconstruct it ---
    GT_PATH = "D:/Projects/URIS/URIS/WEMOM_V1/Data/All_Data/music_features.npy"
    if os.path.exists(GT_PATH):
        print("\n--- GT Verification Mode ---")
        try:
            gt_data = np.load(GT_PATH)
            print(f"Loaded GT Data: {gt_data.shape}. Mean={gt_data.mean():.4f}, Std={gt_data.std():.4f}")
            
            # Test first 10 samples
            for g_idx in range(10):
                gt_sample = gt_data[g_idx:g_idx+1] # shape (1, 640)
                
                z_gt_tensor = torch.from_numpy(gt_sample).float().to(device)
                with torch.no_grad():
                    logits_gt = model.global_decoder(z_gt_tensor, steps=STEPS)
                    # Use Sampling
                    probs_gt = torch.softmax(logits_gt, dim=-1)
                    predicted_ids_gt = torch.multinomial(probs_gt.view(-1, EVENT_DIMS), 1).view(1, STEPS).cpu().numpy()
                
                ids_gt = predicted_ids_gt[0]
                
                clean_ids_gt = []
                for token in ids_gt:
                    if token == 1: break
                    if token >= 2: clean_ids_gt.append(token)
                
                unique_gt, counts_gt = np.unique(ids_gt, return_counts=True)
                top_5 = sorted(zip(unique_gt, counts_gt), key=lambda x: x[1], reverse=True)[:5]
                print(f"GT Sample {g_idx} Dist: {top_5}")
                
                # If diverse, save it
                if len(unique_gt) > 5:
                     print(f"  -> VALID GT FOUND at index {g_idx}! Saving...")
                     if hasattr(mpe, 'decode'):
                        midi_gt = mpe.decode(clean_ids_gt, strip_extraneous=True)
                        target_gt = OUTPUT_MIDI_PATH.replace('.mid', f'_GT_{g_idx}.mid')
                        import shutil
                        shutil.move(midi_gt, target_gt)
                        print(f"  -> Saved to {target_gt}")
        except Exception as e:
            print(f"GT Check failed: {e}")
            import traceback
            traceback.print_exc()
    else:
        print(f"GT File not found at {GT_PATH}, skipping verification.")
    
    print("\n--- Model Generation Mode ---")
    
    # Check validity (dead zone check)
    std_val = z.std()
    
    # Define scaling factors to try
    # 1.0: As is
    # Scale to 4.4 (GT Std)
    # Scale to 1.0 (Standard Normal)
    scales = [1.0]
    if abs(std_val - 4.4) > 1.0:
        scales.append(4.4 / std_val)
    if abs(std_val - 1.0) > 0.5:
        scales.append(1.0 / std_val)
        
    print(f"Will try scaling factors: {scales}")
    
    z_tensor_orig = torch.from_numpy(z).float().to(device)
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(OUTPUT_MIDI_PATH), exist_ok=True)

    for scale in scales:
        print(f"\n--- Decoding with Scale {scale:.4f} (Eff Std: {std_val * scale:.4f}) ---")
        z_input = z_tensor_orig * scale
        
        with torch.no_grad():
            logits = model.global_decoder(z_input, steps=STEPS)
            
            if USE_SAMPLING:
                # Apply Temperature
                logits = logits / TEMPERATURE
                probs = torch.softmax(logits, dim=-1)
                predicted_ids = torch.multinomial(probs.view(-1, EVENT_DIMS), 1).view(z.shape[0], STEPS).cpu().numpy()
            else:
                predicted_ids = torch.argmax(logits, dim=-1).cpu().numpy()

        for i, ids in enumerate(predicted_ids):
            # Inspect output for debugging
            unique, counts = np.unique(ids, return_counts=True)
            sorted_counts = sorted(zip(unique, counts), key=lambda x: x[1], reverse=True)
            print(f"Sample {i} Top 5 Events: {sorted_counts[:5]}")
            
            # Filter IDs: Remove Reserved (0, 1) to avoid encoder crash
            # We ignore EOS (1) to force fixed length generation matching STEPS
            clean_ids = []
            for token in ids:
                # User requested fixed length, so we disable EOS truncation
                # if token == 1: # EOS 
                #     break
                if token >= 2: # Valid Event
                    clean_ids.append(token)
            
            unique_clean = len(set(clean_ids))
            
            # Check if it's all padding (0) or TimeShift (178)
            # 178 is TimeShift 1 (10ms). Repeated 178 means silence.
            # 0 is padding.
            
            if unique_clean < 5:
                print(f"-> Result appears to be Silence/Padding (Unique Events: {unique_clean}).")
            else:
                print(f"-> Result appears valid (Unique Events: {unique_clean})!")
            
            
            # mpe.decode expects a list of ints
            # It also handles stripping 0s and EOS if strip_extraneous=True
            # But we filtered manually to be safe.
        
            # mpe.decode expects a list of ints
            # It also handles stripping 0s and EOS if strip_extraneous=True
            # But we filtered manually to be safe.
            midi_temp = mpe.decode(clean_ids, strip_extraneous=True)
            
            # Save with scale suffix
            import shutil
            suffix = "" if scale == 1.0 else f"_scale_{scale:.2f}"
            target = OUTPUT_MIDI_PATH.replace('.mid', f'{suffix}.mid')
            if len(predicted_ids) > 1:
                target = target.replace('.mid', f'_{i}.mid')
            
            # Robust Move/Copy
            try:
                if os.path.exists(target):
                    os.remove(target)
                shutil.copy2(midi_temp, target)
                # os.remove(midi_temp) # Optional cleanup
                print(f"Successfully saved MIDI to: {target}")

                # ==========================================
                # POST-PROCESSING: Music Theory Filter (Rule-based Constraint)
                # ==========================================
                if USE_FILTER:
                    try:
                        # Modified for HCI Rules
                        from WEMOM_V1.EmoMusic.music_theory_filter_original import MusicTheoryFilter
                        
                        print(f"Applying MusicTheoryFilter V2 (Valence={USER_VALENCE}, Arousal={USER_AROUSAL})...")
                        mtf = MusicTheoryFilter(quantization_step=0.25)
                        
                        # Apply New Interactive Constraints
                        mtf.apply_constraints(target, target, valence=USER_VALENCE, arousal=USER_AROUSAL)
                        
                        print(f"-> Filter Applied Successfully.")
                    except ImportError:
                        print("Warning: music_theory_filter module not found.")
                    except Exception as e:
                        print(f"Error applying filter: {e}")

            except Exception as e:
                print(f"File copy failed: {e}")

    
               
    
if __name__ == "__main__":
    reconstruct()
